import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className={style.container}>
   <div className={style.heading}>
    <h1>BREAKING BAD MANIA</h1>
    <p>A high school chemistry teacher diagnosed with inoperable <br /> lung cancer turns to manufacturing and selling <br /> methamphetamine in order to secure his family's future.</p>
   </div>
    </div>
     
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
